repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        files: ^python_analytics/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^python_analytics/.*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]
        files: ^python_analytics/.*\.py$

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        files: ^models/.*\.sql$
        args: [--dialect, duckdb, --config, .sqlfluff]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-fix
        files: ^models/.*\.sql$
        args: [--dialect, duckdb, --config, .sqlfluff]
        stages: [manual]

  - repo: local
    hooks:
      - id: dbt-test
        name: dbt test
        entry: dbt test
        language: system
        pass_filenames: false
        files: ^models/.*\.sql$
        stages: [manual]

      - id: dbt-docs-generate
        name: dbt docs generate
        entry: dbt docs generate
        language: system
        pass_filenames: false
        files: ^models/.*\.sql$
        stages: [manual]
