
# Project name: Use lowercase characters and underscores.
# A good name reflects your organization or the models' purpose.
name: 'ecom_analytics_platform'
version: '2.0.0'
config-version: 2

profile: 'ecom_analytics_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"


# Model Configurations
# For more details, see the dbt documentation: https://docs.getdbt.com/docs/configuring-models

# The following configurations apply to all models in the project.
# These settings can be overridden in individual model files.
models:
  ecom_analytics_platform:
    # Raw Layer: Contains immutable copies of source data.
    raw:
      +materialized: table
      +docs:
        node_color: "#FF6B6B"
      +tags: ["raw", "source"]
    
    # Staging Layer: Applies light transformations and standardization.
    staging:
      +materialized: view
      +docs:
        node_color: "#4ECDC4"
      +tags: ["staging", "transformation"]
    
    # Intermediate Layer: Implements business logic and complex transformations.
    intermediate:
      +materialized: view
      +docs:
        node_color: "#45B7D1"
      +tags: ["intermediate", "business_logic"]
    
    # Marts Layer: Provides production-ready data models for analytics.
    marts:
      +materialized: table
      +docs:
        node_color: "#96CEB4"
      +tags: ["marts", "production"]
      
      # Core business domain models.
      core:
        +materialized: table
        +meta:
          owner: "analytics_team"
          domain: "core_business"
        +tags: ["core", "business_critical"]
      
      # Financial analytics models with incremental updates.
      finance:
        +materialized: incremental
        +unique_key: "transaction_id"
        +on_schema_change: "fail"
        +incremental_strategy: "append"
        +tags: ["finance", "incremental"]
        +meta:
          owner: "finance_team"
          refresh_frequency: "daily"
      
      # Marketing and customer analytics models.
      marketing:
        +materialized: table
        +tags: ["marketing", "customer_analytics"]
        +meta:
          owner: "marketing_team"
          domain: "customer_insights"

# Global variables for use in models.
vars:
  # Date and time settings.
  current_date: "{{ run_started_at.strftime('%Y-%m-%d') }}"
  lookback_days: 365
  cohort_analysis_months: 24
  partner_performance_lookback_days: 30
  
  # Business KPI and performance thresholds.
  revenue_target_monthly: 2000000
  high_value_order_threshold: 1000
  customer_ltv_threshold: 5000
  churn_risk_threshold: 0.7
  
  # Data quality and monitoring settings.
  data_quality_error_threshold: 0.02
  freshness_threshold_hours: 6
  row_count_variance_threshold: 0.1
  
  # Advanced analytics configurations.
  seasonality_periods: [7, 30, 90, 365]
  forecasting_horizon_days: 90
  anomaly_detection_sensitivity: 0.95
  
  # Feature engineering parameters.
  feature_engineering_window: 90
  embedding_dimensions: 128
  clustering_max_k: 10

# Configuration for dbt tests.
tests:
  +severity: "error"
  +store_failures: true
  +store_failures_as: "table"

# Configuration for data snapshots.
snapshots:
    +target_schema: "snapshots"
    +strategy: "timestamp"
    +updated_at: "updated_at"

# Configuration for seed files.
seeds:
    +schema: "reference_data"
    +materialized: table
    +docs:
      node_color: "#F7DC6F"

# Hooks for executing custom operations.
on-run-start:
  - "{{ log('Starting dbt run at ' ~ run_started_at, info=true) }}"

on-run-end:
  - "{{ log('Completed dbt run at ' ~ run_started_at, info=true) }}"

# Database quoting settings.
quoting:
  database: false
  schema: false
  identifier: false
