ecom_analytics_platform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: data/ecom_warehouse.duckdb
      database: ecom_warehouse
      schema: main
    prod:
      type: duckdb
      path: data/prod_warehouse.duckdb
      database: prod_warehouse
      schema: main