version: 2

sources:
  - name: raw_files
    description: Raw e-commerce data files from various sources
    schema: main
    tables:
      - name: amazon_sales
        external:
          location: '/Users/shabhrishreddyuddehal/Downloads/dbt/data/raw/Amazon Sale Report.csv'
          using: csv
        description: Raw Amazon sales data with order details, customer segments, and geo-location
        columns:
          - name: "Order ID"
            description: Unique identifier for each order
          - name: "Date"
            description: Order date
          - name: "Status"
            description: Order status
          - name: "Amount"
            description: Order amount
          - name: "SKU"
            description: Product SKU
      
      - name: international_sales
        external:
          location: '/Users/shabhrishreddyuddehal/Downloads/dbt/data/raw/International sale Report.csv'
          using: csv
        description: International sales data with customer and product details
        columns:
          - name: "DATE"
            description: Order date
          - name: "CUSTOMER" 
            description: Customer name
          - name: "SKU"
            description: Product SKU
          - name: "GROSS AMT"
            description: Gross amount
      
      - name: product_catalog
        external:
          location: '/Users/shabhrishreddyuddehal/Downloads/dbt/data/raw/P  L March 2021.csv'
          using: csv
        description: Product catalog with marketplace pricing data
        columns:
          - name: "Sku"
            description: Product SKU
          - name: "Category"
            description: Product category
          - name: "Amazon MRP"
            description: Amazon marketplace price
      
      - name: inventory
        external:
          location: '/Users/shabhrishreddyuddehal/Downloads/dbt/data/raw/Sale Report.csv'
          using: csv
        description: Inventory and stock data
        columns:
          - name: "SKU Code"
            description: Product SKU code
          - name: "Stock"
            description: Current stock level
          - name: "Category"
            description: Product category