version: 2

models:
  # Legacy models (to be deprecated)
  - name: dim_products
    description: Dimension table containing unique product information.
    columns:
      - name: product_sku
        description: Unique identifier for the product.
        tests:
          - not_null
      - name: product_category
        description: Category of the product (e.g., 'electronics', 'clothing').
        tests:
          - not_null

  - name: dim_dates
    description: Dimension table for dates.
    columns:
      - name: date_day
        description: The specific date.
        tests:
          - unique
          - not_null

  - name: fct_order_items
    description: Fact table for individual order line items.
    columns:
      - name: order_id
        description: Identifier for the order.
        tests:
          - not_null
      - name: product_sku
        description: Foreign key to the dim_products table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_sku
      - name: item_revenue_amount
        description: The monetary revenue generated by this item in the order.
      - name: quantity
        description: The quantity of the product in the order line item.
        tests:
          - not_null

  - name: agg_daily_sales
    description: Aggregated daily sales metrics by product category and fulfillment method.
    columns:
      - name: order_date
        description: The date of the aggregated sales.
      - name: daily_revenue
        description: Total revenue for the day for the given category/fulfillment.

  # Advanced Analytics Models
  - name: mart_partner_performance_dashboard
    description: >
      Comprehensive partner performance dashboard providing real-time insights for ZMS Central Analytics Engineering team.
      This model serves as the primary source of truth for partner performance metrics, enabling data-driven decisions 
      for partner optimization and strategic planning.
    
    columns:
      - name: dashboard_key
        description: Unique identifier for dashboard records
        tests:
          - not_null
          - unique
      
      - name: partner_channel
        description: Channel through which the partner operates (amazon, merchant_website, international)
        tests:
          - not_null
          - accepted_values:
              values: ['amazon', 'merchant_website', 'international']
      
      - name: customer_segment
        description: Customer segment classification (b2b, b2c)
        tests:
          - not_null
          - accepted_values:
              values: ['b2b', 'b2c']
      
      - name: revenue_30d
        description: Total revenue in the last 30 days
        tests:
          - not_null
      
      - name: overall_health_score
        description: Overall partner health score (0-100)
        tests:
          - not_null
      
      - name: recommended_action
        description: System-generated recommendation for partner management
        tests:
          - not_null
          - accepted_values:
              values: ['maintain_current_strategy', 'optimize_operations', 'strategic_review_needed', 'immediate_action_required']

  - name: mart_financial_performance_summary
    description: >
      Incremental financial performance summary providing executive-level insights for strategic decision-making.
      This model supports financial reporting, trend analysis, and risk assessment for the ZMS business.
    
    columns:
      - name: financial_summary_key
        description: Unique identifier for financial summary records
        tests:
          - not_null
          - unique
      
      - name: order_date
        description: Date of the financial transaction
        tests:
          - not_null
      
      - name: daily_revenue
        description: Total revenue for the day
        tests:
          - not_null
      
      - name: daily_gross_margin_rate
        description: Gross margin rate for the day
        tests:
          - not_null
      
      - name: performance_classification
        description: Performance classification based on key metrics
        tests:
          - not_null
          - accepted_values:
              values: ['excellent', 'good', 'needs_improvement', 'poor']

  - name: mart_partner_optimization_insights
    description: >
      Advanced partner optimization insights with AI-driven recommendations for strategic partner management.
      This model provides benchmarking, gap analysis, and actionable insights for partner performance improvement.
    
    columns:
      - name: optimization_key
        description: Unique identifier for optimization insights
        tests:
          - not_null
          - unique
      
      - name: partner_channel
        description: Partner channel identifier
        tests:
          - not_null
      
      - name: strategic_classification
        description: Strategic classification of the partner
        tests:
          - not_null
          - accepted_values:
              values: ['star_performer', 'solid_performer', 'potential_improver', 'needs_attention', 'underperformer']
      
      - name: optimization_priority_score
        description: Priority score for optimization efforts (0-100)
        tests:
          - not_null
      
      - name: specific_recommendation
        description: Specific actionable recommendation for partner optimization
        tests:
          - not_null

  - name: mart_cohort_analysis
    description: >
      Advanced cohort analysis for customer lifecycle understanding and revenue forecasting.
      This model enables customer retention analysis, lifetime value prediction, and cohort-based strategic planning.
    
    columns:
      - name: cohort_analysis_key
        description: Unique identifier for cohort analysis records
        tests:
          - not_null
          - unique
      
      - name: cohort_month
        description: Month when the cohort was first acquired
        tests:
          - not_null
      
      - name: period_number
        description: Number of months since cohort acquisition
        tests:
          - not_null
      
      - name: retention_rate
        description: Percentage of original cohort still active
        tests:
          - not_null
      
      - name: cohort_quality_score
        description: Overall quality score of the cohort (0-100)
        tests:
          - not_null

  - name: dim_customer_segments
    description: >
      Customer segmentation dimension with advanced analytics and behavioral insights.
      This model provides comprehensive customer profiling, segmentation, and strategic recommendations.
    
    columns:
      - name: customer_segment_key
        description: Unique identifier for customer segments
        tests:
          - not_null
          - unique
      
      - name: customer_segment
        description: Primary customer segment classification
        tests:
          - not_null
          - accepted_values:
              values: ['b2b', 'b2c']
      
      - name: strategic_segment
        description: Strategic business segment classification
        tests:
          - not_null
      
      - name: estimated_annual_value
        description: Estimated annual value of the customer segment
        tests:
          - not_null
      
      - name: clv_tier
        description: Customer lifetime value tier
        tests:
          - not_null
          - accepted_values:
              values: ['platinum', 'gold', 'silver', 'bronze', 'basic']

  - name: dim_product_intelligence
    description: >
      Enhanced product dimension with AI-driven insights and performance analytics.
      This model provides comprehensive product analysis, strategic classification, and optimization recommendations.
    
    columns:
      - name: product_intelligence_key
        description: Unique identifier for product intelligence records
        tests:
          - not_null
          - unique
      
      - name: product_sku
        description: Product SKU identifier
        tests:
          - not_null
      
      - name: product_category
        description: Product category classification
        tests:
          - not_null
      
      - name: product_score
        description: Comprehensive product performance score (0-100)
        tests:
          - not_null
      
      - name: strategic_classification
        description: Strategic classification of the product
        tests:
          - not_null
          - accepted_values:
              values: ['cash_cow', 'rising_star', 'sunset_product', 'question_mark', 'core_product']
      
      - name: recommended_action
        description: Recommended strategic action for the product
        tests:
          - not_null

# Data quality tests for multiple models
tests:
  - name: revenue_consistency_check
    description: Ensures revenue consistency across models
    config:
      severity: error
    sql: |
      with partner_revenue as (
        select sum(revenue_30d) as total_revenue
        from {{ ref('mart_partner_performance_dashboard') }}
      ),
      financial_revenue as (
        select sum(daily_revenue) as total_revenue
        from {{ ref('mart_financial_performance_summary') }}
        where order_date >= current_date - interval '30 days'
      )
      select *
      from partner_revenue p
      cross join financial_revenue f
      where abs(p.total_revenue - f.total_revenue) > 1000

  - name: data_freshness_check
    description: Ensures data freshness across critical models
    config:
      severity: warn
    sql: |
      select 'mart_partner_performance_dashboard' as model_name, dashboard_updated_at as last_update
      from {{ ref('mart_partner_performance_dashboard') }}
      where dashboard_updated_at < current_timestamp - interval '{{ var("freshness_threshold_hours") }}' hour
      
      union all
      
      select 'mart_financial_performance_summary' as model_name, summary_created_at as last_update
      from {{ ref('mart_financial_performance_summary') }}
      where summary_created_at < current_timestamp - interval '{{ var("freshness_threshold_hours") }}' hour

  - name: partner_performance_anomaly_detection
    description: Detects significant performance anomalies
    config:
      severity: warn
    sql: |
      select 
        partner_channel,
        customer_segment,
        revenue_30d,
        overall_health_score
      from {{ ref('mart_partner_performance_dashboard') }}
      where (
        (revenue_30d > 0 and overall_health_score < 20) or
        (revenue_30d < 1000 and overall_health_score > 80) or
        (revenue_growth_30d < -0.5 and recommended_action = 'maintain_current_strategy')
      )

sources:
  - name: audit_log
    description: System audit logs for data quality monitoring